### ISSUE TITLE
User login and logout functionality

### ISSUE THREAD

**Issue by Pythonian** [zuri-training/Col_Films_Proj_Team_113#15]
**Description**

Create a Login and Logout functionality for authenticated users of the system.

Expected to work on:

- [ ] The views.py file
- [ ] The urls.py file
- [ ] The forms.py file
- [ ] Set login and logout configurations in the settings

**Guides**

* Make use of Django's built-in authentication package
* Make use of internalization where necessary

_Please add a comment below for any added tasks or ask for clarifications._

**Comment by obafemitope50** [comment]
All done, issue closed
