### ISSUE TITLE
FRONT END DEVELOPMENT OF FORGOT PASSWORD PAGE

### ISSUE THREAD

**Issue by Dubuiz** [zuri-training/Col_Films_Proj_Team_113#2]
@nicholasikiroma 

forgot password page 1,2
https://www.figma.com/file/tNI2fUodbSyrhaBGbOxiV9/Col-films-designs?node-id=769%3A1307

**Comment by Pythonian** [comment]
The PR #20 for this issue has been merged with the repository.
