### ISSUE TITLE
Frequently Asked Questions (Backend)

### ISSUE THREAD

**Issue by Pythonian** [zuri-training/Col_Films_Proj_Team_113#31]
**Description**

Create a FAQ backend database and logic where the administrator can enter questions and answers of what is perceived to be the most frequently asked questions by users of the site. 

Querying parameters of the questions from the database to be rendered in the frontend will be up to you to decide.

Hint:
1. You can either query randomly, so for every time the user will refresh the FAQ page, a new set of questions will appear or
2. You can query based on the date the FAQ was created by the admin.

Create a new Django app for this task. It should make use of the `config` project settings.

**Comment by obafemitope50** [comment]
Is this issue still open?
