### ISSUE TITLE
UX Research

### ISSUE THREAD

**Issue by Olamibennie** [zuri-training/Col_Films_Proj_Team_113#41]
I was assigned the lead team for the UX Research for our project team and here's my findings for our project's UX research.

**Comment by Olamibennie** [comment]
Nigerian university students are faced with  challenges of pushing their movie content to a larger audience so as to showcase their talents due to unavailability of a platform that is specifically created for students where they can upload or watch movies tailored for their type of audience or interest.

**Comment by Olamibennie** [comment]
> The problem statement of our project research was a joint effort by myself, Samihah and Adebola.

**Comment by Chiomaojo** [comment]
Being part of the UX team alongside @Olamibennie @Adedeji24 @Schnoookums , we conducted the UX research.
