### ISSUE TITLE
Empathy map and other research findings

### ISSUE THREAD

**Issue by Olamibennie** [zuri-training/Col_Films_Proj_Team_113#51]
After we interviewed our participants, we went to use our findings to understand the challenges of our participants and how to solve their challenges using Empathy map, User Persona, User Story.
Kindly find below the link to our figma file.
https://www.figma.com/file/6zM4baDHJZP185RKMc0YLX/Col-films-research?node-id=0%3A1

**Comment by Olamibennie** [comment]
This issue was marked closed by @Olamibennie, @emmanuellabubakar, @Schnoookums, @Adedeji24, @Chiomaojo, @StellaChinenye

**Comment by Chiomaojo** [comment]
Being part of the UX Research team, we used our findings to create an empathy map where we brainstormed, found out pain points and design features and this was achieved with the help of other team members; @emmanuellabubakar @Olamibennie @StellaChinenye @Schnoookums
