### ISSUE TITLE
Video Upload and Detail Page

### ISSUE THREAD

**Issue by barrerkat** [zuri-training/Col_Films_Proj_Team_113#8]
**Description**

You are required to create the form that will enable creators upload a Video, and a corresponding page where the uploaded video can be viewed.

- [ ] Create two model classes for the Video and Comment
- [ ] Create the form and views that will handle Video upload
- [ ] Make a research on how to restrict video uploads to a max of 15 mins using either client side (Javascript) or backend (Python) techniques.
- [ ] Create a detail view for a Video instance
- [ ] Enable addition of comments to a Video by users

**Comment by Pythonian** [comment]
The Video upload screen for an idea is here: https://www.figma.com/file/HmFzbwjxQiDFUxPYxsp8Q6/Col-films-designs-(Copy)?node-id=2557%3A15720

**Comment by Pythonian** [comment]
The Video detail screen is available here: https://www.figma.com/file/HmFzbwjxQiDFUxPYxsp8Q6/Col-films-designs-(Copy)?node-id=2540%3A14223

**Comment by Pythonian** [comment]
@Klinteen Please ask any further questions here if you need clarifications or guides on how to work on this feature.
