### ISSUE TITLE
User Library Feature

### ISSUE THREAD

**Issue by Pythonian** [zuri-training/Col_Films_Proj_Team_113#80]
**Description**

The library page of this project is where users will see Videos they have added to their **Watch Later**, **History** of watched videos and a **Collection** feature for videos.

@obafemitope50 Let's discuss via the comments how the logic for this task will pan out. I'll be dropping some ideas here too.

**Comment by obafemitope50** [comment]
Reporting for duty sir.
Do i need to download a library o django can handle all the functions.

Earlier after my last PR I ran into a merge conflict on my PC. I had to clone to a new folder. I hope that's not an issue

**Comment by Pythonian** [comment]
For now, you don't need to install any library. Django can handle most of the features here.

**Comment by Pythonian** [comment]
By cloning to a new folder, what did you do please?

**Comment by obafemitope50** [comment]
All i did , was to clone the repo from github. to the new folder.instead of git pull. Git pull didn't work because I had merge conflicts. or maybe it did. But I couldn't leave that branch without resolving the issue

**Comment by obafemitope50** [comment]
On the User library features. I'm believing there is already a function for "watch video" or "add to collection". Maybe we can create a trigger function in django. It saves the video id or URL to a like library. idk if that makes sense. Idont know how collections would work but I feel like it could work like the "watch later".

There is a video app in the backend project right?. Just let me know what you think

**Comment by obafemitope50** [comment]
Im waiting for your feedback but to not be idle. For the WatchLater i Created
-a WatchLater model containing 2 fields the content id and the username "user". 
-connected it to the admin.py,, so as to be able to handle it in admins page
-a simple URL.py  that is supposed to lead to where the watchedvideo is at.
-I believe our template should have a "watch later button" , we can use an a tag to connect that to the URL of the watched videos with a pk of the id
-A simple view.py that' , I'm not exactly sure how it'll go but. It should have an if statement. and redirect some also.

**Comment by Pythonian** [comment]
Okay I'll get back to you in the next one hour please. I've had a rough few hours.

**Comment by obafemitope50** [comment]
welldone. I beleive im done with this. But really to have a template neither have I tested the codes out. ill push the codes soon
